School/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin
#  import django.contrib.auth.views

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
    # url(r'^accounts/login/$', django.contrib.auth.views.login, name='login'),
    # url(r'^accounts/logout/$', django.contrib.auth.views.logout, name='logout', kwargs={'next_page': '/'}),
    url(r'^auth/', include('loginsys.urls')),
    url(r'^rank/', include('rank.urls')),
    url(r'', include('blog.urls')),
]

# if settings.DEBUG:
#     urlpatterns += url(r'^media/(?P<path>.*)', 'django.views.static', {'document_root': settings.MEDIA_ROOT})

blog/urls.py
from django.conf.urls import url
from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^post/(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^post/new/$', views.post_new, name='post_new'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),
    url(r'^post/(?P<pk>\d+)/like/(?P<page>\d+)/$', views.add_like, name='add_like'),
    # url(r'^like/$', views.add_like, name='add_like'),
    url(r'^post/(?P<pk>\d+)/comments/$', views.PostComments.as_view(), name='post_comments'),
    url(r'^drafts/$', views.post_draft_list, name='post_draft_list'),
    url(r'^post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),
    url(r'^post/(?P<pk>\d+)/remove/$', views.post_remove, name='post_remove'),
    url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name='comment_approve'),
    url(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
]

polls/urls.py
from django.conf.urls import url
from django.contrib.auth import login, logout
from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),  # /polls/
    url(r'^new/$', views.CreateView.as_view(), name='new'),  # /polls/new/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),  # /polls/5/
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),  # /polls/5/results/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),  # /polls/5/vote/
    url(r'^login/', login, {'template_name': 'core/login.html'}),
]

polls/models.py
from __future__ import unicode_literals
from django.db import models
from django.utils import timezone
from django.conf import settings
import datetime


class Question(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    file = models.FileField()
    # image = models.ImageField()  # Pillow package required

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='choices')
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/forms.py
from django import forms


class QuestionListForm(forms.Form):
    search = forms.CharField(required=False)
    sort_field = forms.ChoiceField(choices=(('id', 'Identifier'),
                                            ('pub_date', 'Publication date'),
                                            ('question_text', 'Text')))


class NewQuestionForm(forms.Form):
    question_text = forms.CharField(widget=forms.Textarea)
    pub_date = forms.DateTimeField(widget=forms.widgets.DateTimeBaseInput)

polls/views.py
from django.shortcuts import get_object_or_404, render_to_response
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.utils import timezone
from django.views import generic
from django.db.models import Count
from django.shortcuts import resolve_url
from .models import Choice, Question
from .forms import QuestionListForm, NewQuestionForm


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_questions'

    def dispatch(self, request, *args, **kwargs):
        self.sort_search_form = QuestionListForm(request.GET)
        self.sort_search_form.is_valid()
        self.search = self.sort_search_form.cleaned_data.get('search')
        self.sort_field = self.sort_search_form.cleaned_data.get('sort_field')
        return super(IndexView, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        queryset = super(IndexView, self).get_queryset().filter(pub_date__lte=timezone.now())  # author=self.request.user
        if self.search:
            queryset = queryset.filter(question_text__icontains=self.search)
        if self.sort_field:
            queryset = queryset.order_by(self.sort_field)[:5]
        queryset = queryset.annotate(choices_count=Count('choices'))
        return queryset

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['sort_search_form'] = self.sort_search_form
        return context


class CreateView(generic.CreateView):
    model = Question
    template_name = 'polls/create.html'
    fields = ('pub_date', 'question_text')

    def dispatch(self, request, *args, **kwargs):
        self.new_question_form = NewQuestionForm(request.POST or None)
        return super(CreateView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(CreateView, self).get_context_data(**kwargs)
        context['new_question_form'] = self.new_question_form
        return context

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(CreateView, self).form_valid(form)

    def get_success_url(self):  # redirect after create
        return resolve_url('polls:detail', pk=self.object.pk)


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    context_object_name = 'question'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'
    context_object_name = 'question'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render_to_response('polls/detail.html', {
            'question': question,
            'error_message': 'You didn\'t select a choice'})
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question_id,)))

polls/templates/polls/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form action="" method="post">
        {% csrf_token %}
        {{ new_question_form }}
        <input type="submit">
    </form>
</body>
</html>

polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Question</title>
</head>
<body>
    <h1>{{ question.question_text }}</h1>

    {{ question.file.url }}
    
    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}

    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
            <br>
        {% endfor %}
        <input type="submit" value="Vote">
    </form>
</body>
</html>

polls/templates/polls/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Polls</title>
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
</head>
<body>
    {% if latest_questions %}
        <form action="" method="get">
{#            <label for="sort_field">Sort by: </label>#}
{#            <select name="sort_field" id="sort_field">#}
{#                <option value="id">Identifier</option>#}
{#                <option value="pub_date">Publication date</option>#}
{#                <option value="question_text">Text</option>#}
{#            </select>#}
{#            <input type="search" name="search">#}
            {{ sort_search_form.sort_field.label_tag }}
            {{ sort_search_form.sort_field }}
            {{ sort_search_form.search }}
            {{ sort_search_form.sort_field.errors }}
            <input type="submit">
        </form>
        <a href="{% url 'polls:new' %}">Create question</a>
        <ul>
            {% for question in latest_questions %}
                <li>{{ question.author }}
                    <br>
                    <a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No posts are available.</p>
    {% endif %}
</body>
</html>

polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Result</title>
</head>
<body>
    <h1>{{ question.question_text }}</h1>
    <ul>
        {% for choice in question.choice_set.all %}
            <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
        {% endfor %}
    </ul>
    <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
</body>
</html>