School/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin
#  import django.contrib.auth.views

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
    # url(r'^accounts/login/$', django.contrib.auth.views.login, name='login'),
    # url(r'^accounts/logout/$', django.contrib.auth.views.logout, name='logout', kwargs={'next_page': '/'}),
    url(r'^auth/', include('loginsys.urls')),
    url(r'^rank/', include('rank.urls')),
    url(r'', include('blog.urls')),
]

# if settings.DEBUG:
#     urlpatterns += url(r'^media/(?P<path>.*)', 'django.views.static', {'document_root': settings.MEDIA_ROOT})

blog/urls.py
from django.conf.urls import url
from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^post/(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^post/new/$', views.post_new, name='post_new'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),
    url(r'^post/(?P<pk>\d+)/like/(?P<page>\d+)/$', views.add_like, name='add_like'),
    # url(r'^like/$', views.add_like, name='add_like'),
    url(r'^post/(?P<pk>\d+)/comments/$', views.PostComments.as_view(), name='post_comments'),
    url(r'^drafts/$', views.post_draft_list, name='post_draft_list'),
    url(r'^post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),
    url(r'^post/(?P<pk>\d+)/remove/$', views.post_remove, name='post_remove'),
    url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name='comment_approve'),
    url(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
]

loginsys/urls.py
from django.conf.urls import url
from . import views

app_name = 'loginsys'
urlpatterns = [
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^register/$', views.register, name='register'),
]

rank/urls.py
from django.conf.urls import url
from . import views

app_name = 'rank'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^add_category', views.add_category, name='add_category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/$', views.category, name='category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/add_page/$', views.add_page, name='add_page'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
]

blog/models.py
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db import models
from django.utils import timezone


class Post(models.Model):
    class Meta:
        db_table = 'post'
        verbose_name = u'Запись'
        verbose_name_plural = u'Записи'
        ordering = ('-created_date',)

    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    likes = models.IntegerField(default=0)
    # likes = models.ManyToManyField(User, related_name='likes')

    #@property
    #def total_likes(self):
    #    return self.likes.count()

    def get_url(self):
        return reverse('blog:post_detail', kwargs={'pk': self.pk})

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def approved_comments(self):
        return self.comments.filter(approved_comment=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    class Meta:
        db_table = 'comment'
        verbose_name = u'Комментарий'
        verbose_name_plural = u'Комментарии'

    post = models.ForeignKey('blog.Post', related_name='comments')
    author = models.ForeignKey('auth.User')
    text = models.TextField(verbose_name='Comment text')
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

blog/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'text',)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('author', 'text')

blog/views.py
# import json
# from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.core.urlresolvers import reverse
from django.template.context_processors import csrf
from django.views import generic
from django.utils import timezone
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
# from django.views.decorators.http import require_POST

from .models import Post, Comment
from .forms import PostForm, CommentForm


def post_list(request):
    posts = Post.objects\
        .filter(published_date__lte=timezone.now())\
        .order_by('published_date')
    paginator = Paginator(posts, 5)
    page = request.GET.get('page', 1)
    try:
        current_page = paginator.page(page)
    except PageNotAnInteger:
        current_page = paginator.page(1)
    except EmptyPage:
        current_page = paginator.page(paginator.num_pages)
    return render(request, 'blog/post_list.html', {
        'posts': current_page,
        'paginator': paginator,
        'username': auth.get_user(request).username
    })


def post_detail(request, pk):
    comment_form = CommentForm()
    args = {}
    args.update(csrf(request))
    args['post'] = get_object_or_404(Post, pk=pk)
    args['form'] = comment_form
    args['username'] = auth.get_user(request).username
    return render(request, 'blog/post_detail.html', args)


class PostComments(generic.DetailView):
    template_name = 'blog/post_comments.html'
    model = Post
    context_object_name = 'post'


@login_required
def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.POST and ('pause' not in request.session):
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            request.session.set_expiry(60)
            request.session['pause'] = True
    return HttpResponseRedirect(reverse('blog:post_detail', args=(pk,)))


@login_required
def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return HttpResponseRedirect(reverse('blog:post_detail', args=(post.pk,)))
    else:
        form = PostForm()
    return render(request, 'blog/post_edit.html', {'form': form})


@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return HttpResponseRedirect(reverse('blog:post_detail', args=(post.pk,)))
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})


@login_required
def add_like(request, pk, page=1):
    if pk in request.COOKIES:
        return HttpResponseRedirect(reverse('blog:page_post_list', args=(page,)))
    else:
        post = get_object_or_404(Post, pk=pk)
        post.likes += 1
        post.save()
        response = HttpResponseRedirect(reverse('blog:page_post_list', args=(page,)))
        response.set_cookie(pk, 'test')
        return response
# @login_required
# @require_POST
# def add_like(request):
#     if request.method == 'POST':
#         user = request.user
#         pk = request.POST.get('pk')
#         post = get_object_or_404(Post, pk=pk)
#
#         if post.likes.filter(id=user.id).exists():
#             post.likes.remove(user)
#             message = 'You disliked this'
#         else:
#             post.likes.add(user)
#             message = 'You liked this'
#         args = {'likes_count': post.total_likes, 'message': message}
#         return HttpResponse(json.dumps(args), content_type='application/json')


@login_required
def post_draft_list(request):
    posts = Post.objects.filter(published_date__isnull=True).order_by('created_date')
    return render(request, 'blog/post_draft_list.html', {'posts': posts})


@login_required
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return HttpResponseRedirect(reverse('blog:post_detail', args=(pk,)))


@login_required
def post_remove(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    return HttpResponseRedirect(reverse('blog:post_list'))


@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return HttpResponseRedirect(reverse('blog:post_detail', args=(comment.post.pk,)))


@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    return HttpResponseRedirect(reverse('blog:post_detail', args=(post_pk,)))

blog/templates/blog/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="ru-RU">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    <title>School</title>
    <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
</head>
<body>
    <div class="main-title">
        {% if user.is_authenticated %}
            <a href="{% url 'blog:post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
            <a href="{% url 'blog:post_draft_list' %}" class="top-menu"><span class="glyphicon glyphicon-edit"></span></a>
            {#<p class="top-menu">Hello, {{ user.username }} <small>(<a href="{% url 'blog:logout' %}">Log out</a>)</small></p>#}
            <p class="top-menu">Hello, {{ user.username }} <small>(<a href="{% url 'loginsys:logout' %}">Log out</a>)</small></p>
        {% else %}
            {#<a href="{% url 'blog:login' %}" class="top-menu">Sign In</a>#}
            <a href="{% url 'loginsys:login' %}" class="top-menu">Sign In</a>
        {% endif %}
        <h1><a href="{% url 'blog:post_list' %}">My own blog</a></h1>
    </div>

    <div class="content container">
        <div class="row">
            <div class="col-md-offset-1 col-md-12">
                {% block content %}{% endblock %}
                {% block login %}{% endblock %}
            </div>
        </div>
    </div>

    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

blog/templates/blog/post_comments.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>
    {% for comment in post.comments.all %}
        {% if user.is_authenticated or comment.approved_comment %}
            <div class="comment">
                <div class="date">
                    {{ comment.created_date }}
                    {% if not comment.approved_comment %}
                        <a href="{% url 'blog:comment_remove' pk=comment.pk %}" class="btn btn-default"><span class="glyphicon glyphicon-remove"></span></a>
                        <a href="{% url 'blog:comment_approve' pk=comment.pk %}" class="btn btn-default"><span class="glyphicon glyphicon-ok"></span></a>
                    {% endif %}
                </div>
                <strong>{{ comment.author.username }}</strong>
                <p>{{ comment.text|linebreaks }}</p>
            </div>
        {% endif %}
        {% empty %}
            <p>No comments here yet</p>
    {% endfor %}
</body>
</html>

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

<!-- Страница конкретного поста: /post/42/ -->
{% block content %}
    <div class="post-header">
        {% if user.is_authenticated %}
            <a href="{% url 'blog:post_edit' pk=post.pk %}" class="btn btn-default edit">
                <span class="glyphicon glyphicon-pencil"></span>
            </a>
            <a href="{% url 'blog:post_remove' pk=post.pk %}" class="btn btn-default edit">
                <span class="glyphicon glyphicon-remove"></span>
            </a>
        {% endif %}
        {% if post.published_date %}
                <div class="date">
                    {{ post.published_date }}
                </div>
        {% else %}
            {% if user.is_authenticated %}
                <a href="{% url 'blog:post_publish' pk=post.pk %}" class="btn btn-default publish">Publish</a>
            {% endif %}
        {% endif %}
    </div>
    <div class="post">
        <h3>{{ post.title }}</h3>
        <p>{{ post.text|linebreaksbr }}</p>
    </div>

    <hr>

    <div class="comments">
        <div id="comments-list">
        </div>
        {% if user.is_authenticated %}
            <h3>New comment:</h3>
            <form action="{% url 'blog:add_comment_to_post' pk=post.pk %}" method="post" class="post-form">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="save btn btn-default">Send</button>
            </form>
        {% endif %}
    </div>
    <script>
        function load_comments() {
            $("#comments-list").load("{% url 'blog:post_comments' pk=post.pk %}");
        }
        window.setInterval(load_comments, 10000);
    </script>
{% endblock %}

blog/templates/blog/post_draft_list.html
{% extends 'blog/base.html' %}

<!-- Список постов, подготовленных к публикации: /drafts/ -->
{% block content %}
    {% for post in posts %}
        <div class="post">
            <p class="date">created: {{ post.created_date|date:'d-m-Y' }}</p>
            <h3><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h3>
            <p>{{ post.text|truncatechars:200 }}</p>
        </div>
    {% endfor %}
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

<!-- Страница редактирования поста: /post/42/edit/ -->
{% block content %}
    <h3>New Post</h3>
    <form method="POST" class="post-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save Post</button>
    </form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% load staticfiles %}

<!-- Страница всех постов: / или /?page=2 -->
{% block content %}
    <div class="row">
        <div class="col-md-8">
            {% for post in posts %}
                <div class="post">
                    <div class="date">
                        {{ post.published_date }}
                    </div>
                    <h3><a href="{{ post.get_url }}">{{ post.title }}</a></h3>
                    <p>{{ post.text|truncatechars:200 }}</p>
                    <a href="{{ post.get_url }}">Comments: {{ post.approved_comments.count }}</a>
                    <p style="float: right;">
                        <a href="{% url 'blog:add_like' pk=post.pk page=posts.number %}"><img src="{% static 'images/Like.png' %}" width="25px" height="25px"></a>
                        {{ post.likes }}
{#                        <input type="button" id="like" name="{{ post.pk }}" value="Like">#}
{#                        <script>#}
{#                            $('#like').click(function () {#}
{#                                $.ajax({#}
{#                                    type: "POST",#}
{#                                    url: "{% url 'blog:add_like' %}",#}
{#                                    data: {'pk': $(this).attr('name'), 'csrfmiddlewaretoken': '{{ csrf_token }}'},#}
{#                                    success: function (response) {#}
{#                                        alert(response.message);#}
{#                                        alert('Post likes count is now ' + response.likes_count);#}
{#                                    },#}
{#                                    error: function (rs, e) {#}
{#                                        alert(rs.responseText);#}
{#                                    }#}
{#                                });#}
{#                            })#}
{#                        </script>#}
                    </p>
                </div>
                <hr>
            {% endfor %}
        </div>
    </div>
    <div class="row">
        <div class="col-lg-3 col-lg-offset-5">
            <ul class="pagination">
                {% if posts.has_previous %}
                    <li class="arrow"><a href="?page={{ posts.previous_page_number }}">&laquo;</a></li>
                {% else %}
                    <li class="arrow"><a href="">&laquo;</a></li>
                {% endif %}
                {% for page in paginator.page_range %}
                    {% if page == posts.number %}
                        <li class="active">
                    {% else %}
                        <li>
                    {% endif %}
                    <a href="?page={{ page }}">{{ page }}</a></li>
                {% endfor %}
                {% if posts.has_next %}
                    <li class="arrow"><a href="?page={{ posts.next_page_number }}">&raquo;</a></li>
                {% else %}
                    <li class="arrow"><a href="">&raquo;</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
{% endblock %}