School/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin
#  import django.contrib.auth.views

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
    # url(r'^accounts/login/$', django.contrib.auth.views.login, name='login'),
    # url(r'^accounts/logout/$', django.contrib.auth.views.logout, name='logout', kwargs={'next_page': '/'}),
    url(r'^auth/', include('loginsys.urls')),
    url(r'^rank/', include('rank.urls')),
    url(r'', include('blog.urls')),
]

# if settings.DEBUG:
#     urlpatterns += url(r'^media/(?P<path>.*)', 'django.views.static', {'document_root': settings.MEDIA_ROOT})

blog/urls.py
from django.conf.urls import url
from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^post/(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^post/new/$', views.post_new, name='post_new'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),
    url(r'^post/(?P<pk>\d+)/like/(?P<page>\d+)/$', views.add_like, name='add_like'),
    # url(r'^like/$', views.add_like, name='add_like'),
    url(r'^post/(?P<pk>\d+)/comments/$', views.PostComments.as_view(), name='post_comments'),
    url(r'^drafts/$', views.post_draft_list, name='post_draft_list'),
    url(r'^post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),
    url(r'^post/(?P<pk>\d+)/remove/$', views.post_remove, name='post_remove'),
    url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name='comment_approve'),
    url(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
]

loginsys/urls.py
from django.conf.urls import url
from . import views

app_name = 'loginsys'
urlpatterns = [
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^register/$', views.register, name='register'),
]

loginsys/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

loginsys/views.py
from django.contrib import auth
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.template.context_processors import csrf
from django.core.urlresolvers import reverse
from django.contrib.auth.forms import UserCreationForm


def login(request):
    args = {}
    args.update(csrf(request))
    if request.POST:
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return HttpResponseRedirect(reverse('blog:post_list'))
        else:
            args['login_error'] = 'User not found'
            return render(request, 'loginsys/login.html', args)
    else:
        return render(request, 'loginsys/login.html', args)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('blog:post_list'))


def register(request):
    args = {}
    args.update(csrf(request))
    args['form'] = UserCreationForm()
    if request.POST:
        new_user_form = UserCreationForm(request.POST)
        if new_user_form.is_valid():
            new_user_form.save()
            new_user = auth.authenticate(username=new_user_form.cleaned_data['username'], password=new_user_form.cleaned_data['password2'])
            auth.login(request, new_user)
            return HttpResponseRedirect(reverse('blog:post_list'))
        else:
            args['form'] = new_user_form
    return render(request, 'loginsys/register.html', args)

loginsys/templates/loginsys/login.html
{% extends 'blog/base.html' %}

<!-- Страница входа на сайт: /auth/login/ -->
{% block login %}
    <form action="{% url 'loginsys:login' %}" method="post">
        {% csrf_token %}

        <div class="form-group">
            <label for="username">Username: </label>
            <input type="text" name="username" id="username" class="form-control">
        </div>

        <div class="form-group">
            <label for="password">Password: </label>
            <input type="password" name="password" id="password" class="form-control">
        </div>

        {% if login_error %}
            <label class="has-error">{{ login_error }}</label>
        {% endif %}

        <input class="btn btn-success" type="submit" value="Sign in">
        <button class="btn btn-primary"><a style="text-decoration: none; color: white;" href="{% url 'loginsys:register' %}">Register</a></button>
    </form>
{% endblock %}

loginsys/templates/loginsys/register.html
{% extends 'blog/base.html' %}

{% block login %}
    <form action="{% url 'loginsys:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            {{ form.as_p }}
        </div>
        <input type="submit" class="btn btn-success" value="Sign up">
    </form>
{% endblock %}