School/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin
#  import django.contrib.auth.views

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
    # url(r'^accounts/login/$', django.contrib.auth.views.login, name='login'),
    # url(r'^accounts/logout/$', django.contrib.auth.views.logout, name='logout', kwargs={'next_page': '/'}),
    url(r'^auth/', include('loginsys.urls')),
    url(r'^rank/', include('rank.urls')),
    url(r'', include('blog.urls')),
]

# if settings.DEBUG:
#     urlpatterns += url(r'^media/(?P<path>.*)', 'django.views.static', {'document_root': settings.MEDIA_ROOT})

blog/urls.py
from django.conf.urls import url
from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^post/(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^post/new/$', views.post_new, name='post_new'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),
    url(r'^post/(?P<pk>\d+)/like/(?P<page>\d+)/$', views.add_like, name='add_like'),
    # url(r'^like/$', views.add_like, name='add_like'),
    url(r'^post/(?P<pk>\d+)/comments/$', views.PostComments.as_view(), name='post_comments'),
    url(r'^drafts/$', views.post_draft_list, name='post_draft_list'),
    url(r'^post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),
    url(r'^post/(?P<pk>\d+)/remove/$', views.post_remove, name='post_remove'),
    url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name='comment_approve'),
    url(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
]

rank/urls.py
from django.conf.urls import url
from . import views

app_name = 'rank'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^add_category', views.add_category, name='add_category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/$', views.category, name='category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/add_page/$', views.add_page, name='add_page'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
]

rank/models.py
from django.contrib.auth.models import User
from django.db import models
from django.template.defaultfilters import slugify


class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField()
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Categories'


class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username

rank/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Page, Category, UserProfile


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text='Please enter the category name')
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name',)


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text='Please enter the title of the page')
    url = forms.URLField(max_length=200, help_text='Please enter the URL of the page')
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Page
        exclude = ('category',)

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        if url:
            if not url.startswith('https://'):
                if not url.startswith('http://'):
                    url = 'http://' + url
            cleaned_data['url'] = url

        return cleaned_data


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

rank/views.py
from datetime import datetime
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.template.context_processors import csrf

from .models import Category, Page
from .forms import CategoryForm, PageForm, UserForm, UserProfileForm


def index(request):
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]
    args = {'categories': category_list, 'pages': page_list}

    visits = request.session.get('visits')
    if not visits:
        visits = 1
    reset_last_visit_time = False

    last_visit = request.session.get('last_visit')
    if last_visit:
        last_visit_time = datetime.strptime(last_visit[:-7], '%Y-%m-%d %H:%M:%S')
        if (datetime.now() - last_visit_time).days > 0:
            visits += 1
            reset_last_visit_time = True
    else:
        reset_last_visit_time = True

    if reset_last_visit_time:
        request.session['last_visit'] = str(datetime.now())
        request.session['visits'] = visits

    args['visits'] = visits
    response = render(request, 'rank/index.html', args)
    return response


def about(request):
    if request.session.get('visits'):
        count = request.session.get('visits')
    else:
        count = 0

    return render(request, 'rank/about.html', {'visits': count})


def category(request, category_name_slug):
    args = {}
    try:
        category_item = Category.objects.get(slug=category_name_slug)
        args['category_name'] = category_item.name
        args['category_name_slug'] = category_item.slug
        pages = Page.objects.filter(category=category_item)
        args['pages'] = pages
        args['category'] = category_item
    except Category.DoesNotExist:
        pass

    return render(request, 'rank/category.html', args)


def add_category(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return HttpResponseRedirect(reverse('rank:index'))
        else:
            print(form.errors)
    else:
        form = CategoryForm()
    return render(request, 'rank/add_category.html', {'form': form})


def add_page(request, category_name_slug):
    category_item = get_object_or_404(Category, slug=category_name_slug)
    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if category_item:
                page = form.save(commit=False)
                page.category = category_item
                page.views = 0
                page.save()
                return HttpResponseRedirect(reverse('rank:category', args=(category_name_slug,)))
        else:
            print(form.errors)
    else:
        form = PageForm()

    args = {'form': form, 'category': category_item}
    return render(request, 'rank/add_page.html', args)


def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()
    return render(request, 'rank/register.html',
                  {'user_form': user_form, 'profile_form': profile_form, 'registered': registered})


def user_login(request):
    args = {}
    args.update(csrf(request))
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)

        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('rank:index'))
        else:
            args['login_error'] = 'User not found'
            return render(request, 'rank/login.html', args)
    else:
        return render(request, 'rank/login.html', args)


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('rank:index'))

rank/templates/rank/about.html
{% extends 'rank/base.html' %}

{% block title %}About{% endblock %}

{% block body %}
    <div class="page-header">
        <h1>About</h1>
    </div>
    <div>
        <p>You've visited the site on: <strong>{{ visits }} occasion(s).</strong></p>
    </div>
{% endblock %}

rank/templates/rank/add_category.html
{% extends 'rank/base.html' %}

{% block title %}Add category{% endblock %}

{% block body %}
    <div class="page-header">
        <h1>Add category</h1>
    </div>
    <link rel="stylesheet" href="http://getbootstrap.com/examples/signin/signin.css">
    <form role="form" action="{% url 'rank:add_category' category.slug %}" method="post" id="category_form">
        <h2 class="form-signin-heading">Add a new category</h2>
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}
            {{ field }}
        {% endfor %}
        <button class="btn btn-primary" type="submit" name="submit">Add category</button>
    </form>
{% endblock %}

rank/templates/rank/add_page.html
{% extends 'rank/base.html' %}

{% block title %}Add page{% endblock %}

{% block body %}
    <div class="page-header">
        <h1>Add page</h1>
    </div>
    {% if category %}
        <link rel="stylesheet" href="http://getbootstrap.com/examples/signin/signin.css">
        <form role="form" action="{% url 'rank:add_page' category.slug %}" method="post" id="page_form">
            <h2 class="form-signin-heading">Add a page to <a href="{% url 'rank:category' category.slug %}">{{ category.name }}</a></h2>
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}
            {% endfor %}
            <button class="btn btn-primary" type="submit" name="submit">Add page</button>
        </form>
    {% else %}
        <p>This category does not exist.</p>
    {% endif %}
{% endblock %}

rank/templates/rank/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rank_extras %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="x-ua-compatible" content="IE=edge">
    <meta name="viewpoint" content="width=device-width, initial-scale=1">
    <title>Rank | {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'rank:index' %}">Rank</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'rank:index' %}">Home</a></li>
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'rank:logout' %}">Logout</a></li>
                        <li><a href="{% url 'rank:add_category' %}">Add a new category</a></li>
                    {% else %}
                        <li><a href="{% url 'rank:register' %}">Register</a></li>
                        <li><a href="{% url 'rank:login' %}">Sign In</a></li>
                    {% endif %}
                    <li><a href="{% url 'rank:about' %}">About</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-3 col-md-2 sidebar">
                {% block side %}
                    {% get_categories category %}
                {% endblock %}
            </div>
            <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
                <div>
                    {% block body %}{% endblock %}
                </div>
            </div>
        </div>
    </div>

    <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

rank/templates/rank/category.html
{% extends 'rank/base.html' %}

{% block title %}{{ category_name }}{% endblock %}

{% block body %}
    <h1>{{ category_name }}</h1>
    {% if category %}
        {% if pages %}
            <ul>
                {% for page in pages %}
                    <li><a href="{{ page.url }}">{{ page.title }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <strong>No pages currently in category.</strong>
        {% endif %}
        <br>
        {% if user.is_authenticated %}
            <a href="{% url 'rank:add_page' category.slug %}">Add new Page</a>
        {% endif %}
    {% else %}
        The specified category {{ category_name }} does not exist!
    {% endif %}
{% endblock %}

rank/templates/rank/cats.html
{% load staticfiles %}

<ul class="nav nav-sidebar">
    {% if cats %}
        {% for category in cats %}
            {% if category == act_cat %}
                <li class="active">
            {% else %}
                <li>
            {% endif %}
            <a href="{% url 'rank:category' category.slug %}">{{ category.name }}</a></li>
        {% endfor %}
    {% else %}
        <li><strong>There are no category present.</strong></li>
    {% endif %}
</ul>

rank/templates/rank/index.html
{% extends 'rank/base.html' %}

{% block title %}Home page{% endblock %}

{% block body %}
    <div class="page-header">
        {% if user.is_authenticated %}
            <h1>Hello, {{ user.username }}!</h1>
        {% else %}
            <h1>Hello, world!</h1>
        {% endif %}
    </div>
    <div class="row placeholders">
        <div class="col-xs-12 col-sm-6 placeholder">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">Top five categories</h3>
                </div>
            </div>
            {% if categories %}
                <ul class="list-group">
                    {% for category in categories %}
                        <li class="list-group-item"><a href="{% url 'rank:category' category.slug %}">{{ category.name }}</a></li>
                    {% endfor %}
                </ul>
            {% else %}
                <strong>There are no categories present.</strong>
            {% endif %}
        </div>
        <div class="col-xs-12 col-sm-6 placeholder">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">Top five pages</h3>
                </div>
            </div>
            {% if pages %}
                <ul class="list-group">
                    {% for page in pages %}
                        <li class="list-group-item"><a href="{{ page.url }}">{{ page.title }}</a> − {{ page.category.name }}</li>
                    {% endfor %}
                </ul>
            {% else %}
                <strong>There are no pages present.</strong>
            {% endif %}
        </div>
    </div>
    <p>Visits: {{ visits }}</p>
{% endblock %}

rank/templates/rank/login.html
{% extends 'rank/base.html' %}

{% block title %}Login{% endblock %}

{% block body %}
    <link rel="stylesheet" href="http://getbootstrap.com/examples/signin/signin.css">
    <div class="page-header">
        <h1>Login</h1>
    </div>
    <form action="" method="post" id="login_form">
        {% csrf_token %}

        <h2 class="form-signin-heading">Please sign in</h2>

        <label for="username">Username: </label>
        <br>
        <input type="text" id="username" class="form-control" name="username" value="" size="50" required autofocus="" placeholder="Username">
        <br>
        <label for="password">Password: </label>
        <br>
        <input type="password" id="password" class="form-control" name="password" value="" size="50" required placeholder="Password">
        <br>
        {% if login_error %}
            <label>{{ login_error }}</label>
        {% endif %}
        <br>
        <button class="btn btn-lg btn-primary btn-block" type="submit" value="Submit">Sign in</button>
    </form>
{% endblock %}

rank/templates/rank/register.html
{% extends 'rank/base.html' %}

{% block title %}Registration{% endblock %}

{% block body %}
    <h1>Register with rank</h1>
    {% if registered %}
        <strong>Thank you for registering!</strong>
        <br>
    {% else %}
        <link rel="stylesheet" href="http://getbootstrap.com/examples/signin/signin.css">
        <form role="form" action="" method="post" id="user_form" enctype="multipart/form-data">
            <h2 class="form-signin-heading">Sign up here</h2>
            {% csrf_token %}
            <div class="form-group">
                <p class="required">
                    <label for="id_username">Username:</label>
                    <input type="text" class="form-control" placeholder="Enter username" name="username" id="id_username" maxlength="30">
                </p>
                <p class="required">
                    <label for="id_email">E-mail:</label>
                    <input type="email" class="form-control" placeholder="Enter email" name="email" id="id_email">
                </p>
                <p class="required">
                    <label for="id_password">Password:</label>
                    <input type="password" class="form-control" placeholder="Enter password" name="username" id="id_password">
                </p>
                <p class="required">
                    <label for="id_password1">Password (again):</label>
                    <input type="password" class="form-control" placeholder="Enter password (again)" name="password1" id="id_password1">
                </p>
            </div>
            {{ profile_form.as_p }}
            <button type="submit" name="submit" class="btn btn-default">Submit</button>
        </form>
    {% endif %}
{% endblock %}